### ISSUE TITLE
The great puts vs p debate, lets switch

### ISSUE THREAD

**Issue by barnes7td** [Bloc/workshop-curriculum#35]
In Workshop we tell students to debug code with `puts` :

![puts-example](https://cloud.githubusercontent.com/assets/382636/16879942/cd09777c-4a80-11e6-9fbf-8e0518f62ffc.png)

We have had this debate many times and the last time `p` clearly won. `p` is for debugging and `puts` is for user output. That is the designed purpose, though I agree `puts` is used for debugging.

Reasons I don't like teach `puts`:

1. `puts` shows and empty line if the value is `nil`
2. Arrays are outputted as multiline values (and students don't comprehend this is the case early on)
3. puts doesn't show `"` in Strings
4. The output for objects doesn't show instance variables by default, though can be overwritten.

I agree the `p` returning the value is problematic as students often leave in their code, or use it as a return statement, but this is easily correct by the mentor and a good lesson for the student of `p` and return values.

I will open this up to debate, from others @bbugh @jcaudle wanted to pitch in.

@choxi @mikesjewett On an organization note. We have decided and debated this before. And though, I believe in continually questioning what we do. I don't know that we consciously decided to use `puts` over `p`, knowing that was a change in strategy. This to me is intellectual capital (decisions we made in the past) that we don't track and when we pivot or add a new roadmap, we don't always learn or retain the intellectual debate and decisions we made. This is part of why it's hard for us to know where we are going, or if we are progressing, because much of these things get lost. I'm not saying it is easy to track these decisions, but I do think it is important.

**Comment by devtheory** [comment]
When one of my students bumped into this, his code was something like this:

``` ruby
def method_name
  puts "some string"
end
```

He seemed to be confused because he thought the assignment required him to use `puts`. He didn't understand that the spec required a specific string to be returned but because of the behavior of `puts`, his method was returning `nil` instead. We had a good chat about method returns in Ruby and the mysteries of `p` vs `puts` and all was right in the world.

**Comment by bbugh** [comment]
1. From the Ruby perspective, `puts` is for output to stdout, `p` is for debugging. I don't think we should be teaching `puts` for debugging, it stringifies everything which makes it hard to understand.

2. I also don't think we should ever put puts in a method like @devtheory showed, it is one of the biggest things I see students struggle with in the beginning. It's so confusing. I stopped doing it in any of my curriculum until well after they understood return values and methods, and it made a huge difference. Just my experience though.

**Comment by getaaron** [comment]
@barnes7td Does this change require anything besides changing `puts` to `p` in your ninja 🐢  screenshot?

**Comment by barnes7td** [comment]
@getaaron That is all we would need to do, as far as I can tell.

**Comment by barnes7td** [comment]
I wanted time for discussion, before we made the easy fix, though.

**Comment by getaaron** [comment]
OK, since there's a decent amount of consensus, and I haven't seen a single argument for `puts`, I changed it:

![image](https://cloud.githubusercontent.com/assets/789577/16882001/751ebb2e-4a82-11e6-8595-8212a305b187.png)

If anyone thinks we should switch back to `puts`, please tag me in a new issue.

**Comment by mikesjewett** [comment]
@getaaron we use `puts` in nearly every exercise when we provide an example of calling an implemented method:

![image](https://cloud.githubusercontent.com/assets/1168076/16883523/6588a822-4a92-11e6-8c29-c83944ee1ae4.png)

`puts` is probably OK there though, since it's not for debugging purposes. That being said, we explain what `puts` is in the first exercise:

![image](https://cloud.githubusercontent.com/assets/1168076/16883567/9f36eb88-4a92-11e6-8c3c-0e7b3988ea7b.png)

If we want to explain `p` explicitly, we'll have to decide on where to do that.
